@api_url=http://localhost:3001

###
GET {{api_url}}/api/persons

###
GET {{api_url}}/api/persons/aaa

###
DELETE {{api_url}}/api/persons/602abc20f0a5a009eefa06b4

###
POST {{api_url}}/api/persons/
Content-Type: application/json

{
    "name": "Jonne A.",
    "number": "121212"
}

###
GET {{api_url}}/api/blogs

###
POST {{api_url}}/api/blogs/
Content-Type: application/json

{
    "title": "test_title",
    "author": "jonne",
    "url": "http://localhost:3001/blogs/test-title-blog",
    "likes": 0
}
