@api_url=http://localhost:3001

###
GET {{api_url}}/api/persons

###
GET {{api_url}}/api/persons/602ac3840f637813e266c10c

###
DELETE {{api_url}}/api/persons/1

###
POST {{api_url}}/api/persons/
Content-Type: application/json

{
    "name": "Jonne A.",
    "number": "121212"
}