@api_url=http://localhost:3001

###
GET {{api_url}}/api/persons

###
GET {{api_url}}/api/persons/602ac677cb12eb17c1433c0d

###
DELETE {{api_url}}/api/persons/602abc20f0a5a009eefa06b4

###
POST {{api_url}}/api/persons/
Content-Type: application/json

{
    "name": "Jonne A.",
    "number": "121212"
}